root = "."
tmp_dir = "tmp"

[build]
cmd         = "go build -o ./tmp/main ./cmd/api"
bin         = "./tmp/main"
include_ext = ["go", "sql"]   # watch também em .sql (schema/queries)
exclude_dir = ["tmp", "bin", "internal/db/migrations"]
delay       = 200

[misc]
clean_on_exit = true
